/*
Enter your query here.
*/
SELECT CITY, LENGTH(CITY) FROM STATION
ORDER BY LENGTH(CITY), CITY ASC
LIMIT 1

SELECT CITY, LENGTH(CITY) FROM STATION
ORDER BY LENGTH(CITY) DESC, CITY ASC
LIMIT 1;

-- SELECT TOP 1 CITY, LEN(CITY) FROM STATION
-- ORDER BY LEN(CITY), CITY ASC

-- SELECT TOP 1 CITY, LEN(CITY) FROM STATION
-- ORDER BY LEN(CITY) DESC, CITY ASC;